[functions]
  external_node_modules = ["node-fetch"]
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build]
  publish = "public"            # or your actual publish directory
  functions = "netlify/functions"  # or wherever your .js files actually are
